name: Video Processor

on:
  repository_dispatch:
    types: [process-video]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Download Video
        run: |
          echo "Downloading from ${{ github.event.client_payload.file_url }}"
          wget -O original_video.mp4 "${{ github.event.client_payload.file_url }}"

      - name: Process Video with FFmpeg
        run: |
          ffmpeg -i original_video.mp4 -y -c copy -movflags faststart processed_video.mp4

      - name: Upload to Telegram
        run: |
          CHAT_ID="${{ github.event.client_payload.chat_id }}"
          FILE_NAME="${{ github.event.client_payload.file_name }}"
          curl -F video=@"processed_video.mp4" -F caption="✅ Processed File: `${FILE_NAME}`" -F parse_mode="Markdown" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendVideo?chat_id=${CHAT_ID}"
